baseURL = 'https://www.linahabazi.com'
languageCode = 'en-us'
title = 'Lina Habazi'
pluralizelisttitles = false

theme = "art-portfolio"

googleAnalytics = ${{ env.ANALYTICS_ID }}

[module]
  [[module.mounts]]
  source = 'content'
  target = 'content'

  [[module.mounts]]
  source = 'prebuild/public/portfolio'
  target = 'content/portfolio'

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
  mainSections = ["portfolio"]
  test = true

  # Nav links in the side bar

  [[params.navlinks]]
  name = "portfolio"
  displayName = "Portfolio"
  url = "/portfolio"
  draft = false

  [[params.navlinks]]
  name = "bio"
  displayName = "Bio"
  url = "/bio"
  draft = false

  [[params.navlinks]]
  name = "cv"
  displayName = "CV"
  url = "/cv"
  draft = false

  [[params.navlinks]]
  name = "contact"
  displayName = "Contact"
  url = "/contact"
  draft = false

  [[params.navlinks]]
  name = "code-art"
  displayName = "Code Art"
  url = "/code-art"
  draft = true

  [[params.navlinks]]
  name = "reading"
  displayName = "Reading"
  url = "/reading"
  draft = true

  [[params.sociallinks]]
  name = "Instagram"
  url = "instagram.com"

  [[params.sociallinks]]
  name = "Twitter"
  url = "twitter.com"